# Stream Generation Config
websocketserver:
    host: 0.0.0.0
    port: 8889
restapi:
    host: 0.0.0.0
    port: 8888
streams:
    vissim:
        streamVissim1: stream-log-files/vissim/trace_T1_light.json
    sumo:
        streamSumo1: stream-log-files/sumo/testASP_30.sumocfg
        streamSumo2: stream-log-files/sumo/testASP_120.sumocfg
        streamSumo3: stream-log-files/sumo/testASP_180.sumocfg
    simple:
        simpleStream: null
    objdet:
        streamKitti1: stream-log-files/objdet/kitti/yolo4/nt/
player:
    vissim:
        class: VissimPlayer
        path: src/vissim_player.py
    sumo:
        class: SumoPlayer
        path: src/sumo_player.py
    simple:
        class: SimplePlayer
        path: src/simple_player.py
    objdet:
        class: ObjDetPlayer
        path: src/objdet_player.py
templates:
    traffic-json:
        subStreamVehicles: stream-templates/traffic/vehicle_template.json
        subStreamTrafficLights: stream-templates/traffic/traffic_light_template.json
        subStreamTrafficLightsChilds: stream-templates/traffic/traffic_light_template2.json
    traffic-nt:
        subStreamVehicles: stream-templates/traffic/vehicle_template.nt
        subStreamTrafficLights: stream-templates/traffic/trafficLight_template.nt
    traffic-asp:
        subStreamVehicles: stream-templates/traffic/vehicle_template.asp
        subStreamTrafficLights: stream-templates/traffic/traffic_light_template.asp
