# Stream Generation Config
websocketserver:
    host: 0.0.0.0
    port: 8889
restapi:
    host: 0.0.0.0
    port: 8888
streams:
    vissim:
        streamVissim1: stream-log-files/vissim/trace_T1_light.json
    sumo:
        streamSumo1: stream-log-files/sumo/testASP_30.sumocfg
        streamSumo2: stream-log-files/sumo/testASP_120.sumocfg
        streamSumo3: stream-log-files/sumo/testASP_180.sumocfg
    simple:
        simpleStream: null
    perceptionstream:
        stream1: stream-log-files/perceptionstream/2011_09_26_drive_0015
        stream2: stream-log-files/perceptionstream/2011_09_26_drive_0017
        stream3: stream-log-files/perceptionstream/2011_09_26_drive_0018
        stream4: stream-log-files/perceptionstream/2011_09_26_drive_0071
        stream5: stream-log-files/perceptionstream/2011_10_03_drive_0042
player:
    vissim:
        class: VissimPlayer
        path: src/vissim_player.py
    sumo:
        class: SumoPlayer
        path: src/sumo_player.py
    simple:
        class: SimplePlayer
        path: src/simple_player.py
    perceptionstream:
        class: PerceptionStreamPlayer
        path: src/perceptionstream_player.py
templates:
    traffic-json:
        subStreamVehicles: stream-templates/traffic/vehicle_template.json
        subStreamTrafficLights: stream-templates/traffic/traffic_light_template.json
        subStreamTrafficLightsChilds: stream-templates/traffic/traffic_light_template2.json
        backgroundKB: stream-log-files/sumo/traffics_kb_small.json
    traffic-nt:
        subStreamVehicles: stream-templates/traffic/vehicle_template.nt
        subStreamTrafficLights: stream-templates/traffic/trafficLight_template.nt
        backgroundKB: stream-log-files/sumo/traffics_kb_small.nt
    traffic-asp:
        subStreamVehicles: stream-templates/traffic/vehicle_template.asp
        subStreamTrafficLights: stream-templates/traffic/traffic_light_template.asp
        backgroundKB: stream-log-files/sumo/traffics_kb_small.asp
    perceptionstream-jsonld:
        format: json-ld
        context: stream-log-files/perceptionstream/context.json
        backgroundKB: stream-log-files/perceptionstream/kb.json
    perceptionstream-n3:
        format: n3
        backgroundKB: stream-log-files/perceptionstream/kb.n3
    perceptionstream-nt:
        format: nt
        backgroundKB: stream-log-files/perceptionstream/kb.nt
    perceptionstream-asp:
        format: asp
        backgroundKB: stream-log-files/perceptionstream/kb.asp
