# Stream Generation Config
websocketserver:
  host: 0.0.0.0
  port: 59126
restapi:
  host: 0.0.0.0
  port: 59125
streams:
  vissim:
     streamVissim1: /stream-log-files/vissim/race_T1_light.json
     streamVissim2: /stream-log-files/vissim/race_T2_light.json
  sumo:
    streamSumo1:  /stream-log-files/sumo/trace_T1_light.json
  simple:
    simpleStream:  null
player:
  vissim:
    class: VissimPlayer
    path: /src/vissim_player.py
  sumo:
    class: SumoPlayer
    path: /src/sumo_player.py
  simple:
    class: SimplePlayer
    path: /src/simple_player.py
templates:
    vehicle-json: /traffic/vehicle_template.json
    vehicle-nt: /traffic/vehicle_template.nt
